database:
    master:
        engine:  mysql
        host:    127.0.0.1
        port:    3306
        username: root
        password: dba
        db:       dorm_testing
        timezone: Asia/Calcutta

media:
    image:
        width: 1280
        heigth: 800
        